"""Scenario declarations for Flatmate RL built via shared factory helpers."""

from __future__ import annotations

from .scenario_factory import (
    build_buyer_profile,
    build_ground_truth,
    build_post,
    build_seller_profile,
    build_visit_scenario,
)


POSTS = {
    "post_023": build_post(
        post_id="post_023",
        area="Andheri W",
        rent=19000,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=18,
        constraints=["employed_only", "no_loud_music_after_11pm"],
        calendar_slots=["Saturday 11am", "Sunday 5pm"],
        description="Two IT professionals seeking a calm 3rd flatmate. 2BHK in Andheri West, fully furnished.",
    ),
    "post_031": build_post(
        post_id="post_031",
        area="Jogeshwari",
        rent=18500,
        diet="non-veg ok",
        listing_type="1BHK share",
        commute_to_goregaon_mins=12,
        constraints=["employed_only", "ok_with_1bhk_share"],
        calendar_slots=["today 7pm", "tomorrow 7pm", "Saturday 4pm"],
        description="Single professional in Jogeshwari looking for a flatmate. Best commute to Goregaon among the available listings.",
    ),
    "post_019": build_post(
        post_id="post_019",
        area="Andheri W",
        rent=20000,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=22,
        constraints=["employed_only", "no_smoking"],
        calendar_slots=["Sunday 2pm", "Monday 8pm"],
        description="Spacious 2BHK in Andheri West. Looking for a working professional. Non-smokers only.",
    ),
    "post_007": build_post(
        post_id="post_007",
        area="Andheri E",
        rent=15000,
        diet="veg only",
        listing_type="room",
        commute_to_goregaon_mins=35,
        constraints=["veg_only", "employed_only"],
        calendar_slots=["Saturday 10am"],
        description="Room in Andheri East. Strictly vegetarian household.",
    ),
    "post_044": build_post(
        post_id="post_044",
        area="Andheri W",
        rent=24000,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=15,
        constraints=["employed_only"],
        calendar_slots=["Saturday 6pm"],
        description="Premium 2BHK in Andheri West. Can negotiate rent for the right flatmate, but usually above budget.",
    ),
    "post_052": build_post(
        post_id="post_052",
        area="Andheri W",
        rent=19800,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=20,
        constraints=["employed_only", "no_smoking"],
        calendar_slots=["Saturday 1pm", "Sunday 4pm"],
        description="Quiet 2BHK in Andheri West with two product teammates. Good fit for working professionals.",
    ),
    "post_061": build_post(
        post_id="post_061",
        area="Jogeshwari",
        rent=17600,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=16,
        constraints=["employed_only"],
        calendar_slots=["Friday 9pm", "Monday 7pm"],
        description="Affordable Jogeshwari 2BHK share with a relaxed working flatmate. Good commute and flexible move-in.",
    ),
    "post_073": build_post(
        post_id="post_073",
        area="Andheri W",
        rent=18800,
        diet="non-veg ok",
        listing_type="3BHK share",
        commute_to_goregaon_mins=24,
        constraints=["employed_only", "no_partying"],
        calendar_slots=["Saturday 9am", "Monday 6pm"],
        description="Large 3BHK in Andheri West with calm flatmates and a no-partying house rule.",
    ),
    "post_082": build_post(
        post_id="post_082",
        area="Jogeshwari",
        rent=19900,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=14,
        constraints=["employed_only"],
        calendar_slots=["Sunday 7pm", "Tuesday 7pm"],
        description="Well-connected Jogeshwari 2BHK close to stations and offices. Strong commute, but limited viewing slots.",
    ),
    "post_091": build_post(
        post_id="post_091",
        area="Andheri W",
        rent=18200,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=21,
        constraints=["employed_only", "cleanliness_important"],
        calendar_slots=["Tuesday 8pm", "Wednesday 8pm"],
        description="Clean, practical Andheri West flatshare with working flatmates and reasonable rent.",
    ),
    "post_104": build_post(
        post_id="post_104",
        area="Jogeshwari",
        rent=19300,
        diet="non-veg ok",
        listing_type="room",
        commute_to_goregaon_mins=13,
        constraints=["employed_only"],
        calendar_slots=["tomorrow 5pm", "Saturday 6pm"],
        description="Compact Jogeshwari room in a professional setup. Good commute, but limited viewing windows.",
    ),
    "post_117": build_post(
        post_id="post_117",
        area="Andheri W",
        rent=17900,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=26,
        constraints=["employed_only", "quiet_weeknights"],
        calendar_slots=["Sunday 1pm", "Monday 8pm"],
        description="Budget-friendly Andheri West 2BHK share with a quiet weekday setup.",
    ),
    "post_131": build_post(
        post_id="post_131",
        area="Andheri W",
        rent=19400,
        diet="non-veg ok",
        listing_type="2BHK share",
        commute_to_goregaon_mins=19,
        constraints=["employed_only"],
        calendar_slots=["Monday 8pm", "Tuesday 8pm"],
        description="Reliable Andheri West 2BHK share with working flatmates, but only weekday evening visit slots.",
    ),
    "post_132": build_post(
        post_id="post_132",
        area="Jogeshwari",
        rent=18800,
        diet="non-veg ok",
        listing_type="room",
        commute_to_goregaon_mins=17,
        constraints=["employed_only"],
        calendar_slots=["Wednesday 7pm", "Thursday 7pm"],
        description="Compact Jogeshwari room with practical flatmates and midweek-only visit options.",
    ),
}


SCENARIOS = {
    "task_visit_single": build_visit_scenario(
        task_id="task_visit_single",
        label="Single Flatmate Visit",
        difficulty="medium",
        description="Find one suitable flatmate-share listing for a non-veg software professional working in Goregaon East, coordinate a visit time that works for both client and poster, and book the visit.",
        task_post_ids=["post_023", "post_031", "post_019", "post_007", "post_044"],
        buyer_profile=build_buyer_profile(
            budget_max=20000,
            dietary="non-veg",
            areas=["Andheri W", "Jogeshwari"],
            occupation="software engineer at a startup",
            visit_availability=["today after 6pm", "tomorrow after 6pm", "Saturday 11am-5pm"],
            initial_disclosure_fields=["budget", "areas", "occupation"],
        ),
        ground_truth=build_ground_truth(
            optimal_posts=["post_023", "post_031"],
            acceptable_posts=["post_019"],
            dealbreaker_posts=["post_007", "post_044"],
            required_bookings=1,
            required_tool_calls=["store_user_details", "search_posts", "match_location_preference", "get_commute_time", "check_calendar_slots", "contact_poster", "book_viewing"],
            required_info=["budget", "diet", "areas", "occupation", "visit_availability"],
            success_condition="Broker must ask the client for visit availability, call check_calendar_slots for poster availability, propose a time that works for both, and book only after both client and poster explicitly say confirm for that same time.",
            min_viable_turns=6,
        ),
        scenario_creation_config={
            "defer_buyer_creation_until_match": True,
            "expected_answers": {
                "user_type": "buyer",
                "user_sub_type": "flat",
                "budget_max": 20000,
                "dietary": "non-veg",
                "areas": ["Andheri W", "Jogeshwari"],
                "occupation": "software engineer at a startup",
                "visit_availability": ["today after 6pm", "tomorrow after 6pm", "Saturday 11am-5pm"],
                "location_pref_type": "specific_area",
                "price_range_negotiable": False,
                "is_price_range_fixed": False,
            },
        },
        initial_user_message="Hi, I'm looking for a flatmate-share near Goregaon East. My budget is up to Rs. 20,000 and I’m mainly considering Andheri West or Jogeshwari because I work as a software engineer at a startup.",
    ),
    "task_visit_single_hidden_flex": build_visit_scenario(
        task_id="task_visit_single_hidden_flex",
        label="Single Visit With Hidden Flex Slot",
        difficulty="medium",
        description="The client initially shares only one visit slot that does not match any listing calendar. The broker should still find a suitable flat, share the actual available visit slots, and let the client choose a different slot that the client can secretly make work.",
        task_post_ids=["post_023", "post_019", "post_052"],
        buyer_profile=build_buyer_profile(
            budget_max=20000,
            dietary="non-veg",
            areas=["Andheri W", "Jogeshwari"],
            occupation="software engineer at a startup",
            visit_availability=["Tuesday after 6pm"],
            hidden_additional_availability=["Saturday 1pm-5pm", "Sunday 4pm-6pm"],
            initial_disclosure_fields=["budget", "areas", "occupation", "visit_availability"],
        ),
        ground_truth=build_ground_truth(
            optimal_posts=["post_023", "post_052"],
            acceptable_posts=["post_019"],
            dealbreaker_posts=[],
            required_bookings=1,
            required_tool_calls=["store_user_details", "search_posts", "match_location_preference", "get_commute_time", "check_calendar_slots", "contact_poster", "book_viewing"],
            required_info=["budget", "diet", "areas", "occupation", "visit_availability"],
            success_condition="The broker should recognize that the client's initially disclosed Tuesday slot does not match listing calendars, share available Saturday or Sunday visit slots from suitable listings, and complete a booking after the client explicitly confirms one of those alternative slots.",
            min_viable_turns=6,
        ),
        scenario_creation_config={
            "defer_buyer_creation_until_match": True,
            "expected_answers": {
                "user_type": "buyer",
                "user_sub_type": "flat",
                "budget_max": 20000,
                "dietary": "non-veg",
                "areas": ["Andheri W", "Jogeshwari"],
                "occupation": "software engineer at a startup",
                "visit_availability": ["Tuesday after 6pm"],
                "location_pref_type": "specific_area",
                "price_range_negotiable": False,
                "is_price_range_fixed": False,
            },
        },
        initial_user_message="Hi, I’m looking for a flatmate-share around Andheri West or Jogeshwari. My budget is Rs. 20,000, I work in Goregaon East as a software engineer, and Tuesday after 6pm is the slot I can do right now.",
    ),
    "task_visit_multi": build_visit_scenario(
        task_id="task_visit_multi",
        label="Multiple Flatmate Visits",
        difficulty="hard",
        description="The client wants to compare multiple flatmate-share options. Start from a broad pool of relevant listings, shortlist the ones that fit the client's stated availability, ask the client which listings they want to pursue, then coordinate and book at least two non-overlapping visits with explicit client and poster consent.",
        task_post_ids=["post_023", "post_031", "post_019", "post_052", "post_061", "post_073", "post_082", "post_091", "post_104", "post_117", "post_007", "post_044"],
        buyer_profile=build_buyer_profile(
            budget_max=20000,
            dietary="non-veg",
            areas=["Andheri W", "Jogeshwari"],
            occupation="software engineer at a startup",
            visit_availability=["tomorrow after 6pm", "Saturday 11am-5pm", "Sunday 2pm-6pm"],
            initial_disclosure_fields=["budget", "areas", "occupation"],
        ),
        ground_truth=build_ground_truth(
            optimal_posts=["post_023", "post_031", "post_019", "post_052"],
            acceptable_posts=["post_061", "post_073", "post_082", "post_091", "post_104", "post_117"],
            dealbreaker_posts=["post_007", "post_044"],
            required_bookings=2,
            required_tool_calls=["store_user_details", "search_posts", "match_location_preference", "get_commute_time", "check_calendar_slots", "contact_poster", "book_viewing"],
            required_info=["budget", "diet", "areas", "occupation", "visit_availability", "listing_choices"],
            success_condition="Broker must gather visit availability, shortlist listings with matching available slots, ask the client which shortlisted listings they want, check each chosen poster's availability, and book at least two non-overlapping visits only after both the client and each post owner explicitly confirm the same proposed times.",
            min_viable_turns=8,
            schedule_feasible_posts=["post_023", "post_031", "post_019", "post_052"],
            max_schedule_feasible_visits=4,
        ),
        scenario_creation_config={
            "defer_buyer_creation_until_match": False,
            "expected_answers": {
                "user_type": "buyer",
                "user_sub_type": "flat",
                "budget_max": 20000,
                "dietary": "non-veg",
                "areas": ["Andheri W", "Jogeshwari"],
                "occupation": "software engineer at a startup",
                "visit_availability": ["tomorrow after 6pm", "Saturday 11am-5pm", "Sunday 2pm-6pm"],
                "location_pref_type": "specific_area",
                "price_range_negotiable": False,
                "is_price_range_fixed": False,
            },
        },
        initial_user_message="Hi, I want to line up visits for at least two good flatmate-share options before deciding. My budget is Rs. 20,000, I’m focused on Andheri West or Jogeshwari, and I work in Goregaon East as a software engineer.",
    ),
    "task_visit_single_seller_followup": build_visit_scenario(
        task_id="task_visit_single_seller_followup",
        label="Single Visit After Seller Follow-Up",
        difficulty="hard",
        description="The buyer shares real weekend availability, but none of the current listings fit those slots. That buyer conversation ends without a booking. A new seller then contacts the broker to create a fresh listing. The broker must gather the seller's details, store the seller data correctly, check if the new post matches the buyer's stored visit availability, and schedule a visit if the slots line up.",
        task_post_ids=["post_131", "post_132"],
        buyer_profile=build_buyer_profile(
            budget_max=20000,
            dietary="non-veg",
            areas=["Andheri W", "Jogeshwari"],
            occupation="software engineer at a startup",
            visit_availability=["Saturday 4pm", "Sunday 5pm"],
            initial_disclosure_fields=["budget", "areas", "occupation", "visit_availability"],
        ),
        seller_profile=build_seller_profile(
            area="Jogeshwari",
            rent=19500,
            dietary="non-veg ok",
            listing_type="2BHK share",
            occupation_requirement="working professionals only",
            calendar_slots=["Saturday 4pm", "Sunday 5pm"],
            description="2BHK share with one working professional, good commute to Goregaon East",
            commute_to_goregaon_mins=16,
            constraints=["employed_only"],
        ),
        ground_truth=build_ground_truth(
            optimal_posts=["post_dynamic_followup_1"],
            acceptable_posts=[],
            dealbreaker_posts=[],
            required_bookings=1,
            required_tool_calls=["store_user_details", "search_posts", "match_location_preference", "get_commute_time", "check_calendar_slots", "store_seller_details", "check_table_slot_matches", "schedule_table_visit"],
            required_info=["budget", "diet", "areas", "occupation", "visit_availability"],
            success_condition="After the first buyer conversation ends without a booking, the broker must gather the seller's listing details, store the seller data correctly, confirm the new post matches the buyer's stored visit slots, and schedule a visit from the matched table data.",
            min_viable_turns=8,
        ),
        scenario_creation_config={
            "defer_buyer_creation_until_match": False,
            "expected_answers": {
                "user_type": "buyer",
                "user_sub_type": "flat",
                "budget_max": 20000,
                "dietary": "non-veg",
                "areas": ["Andheri W", "Jogeshwari"],
                "occupation": "software engineer at a startup",
                "visit_availability": ["Saturday 4pm", "Sunday 5pm"],
                "location_pref_type": "specific_area",
                "price_range_negotiable": False,
                "is_price_range_fixed": False,
            },
            "followup_seller_expected_answers": {
                "user_type": "seller",
                "user_sub_type": "flat",
                "area": "Jogeshwari",
                "rent": 19500,
                "dietary": "non-veg ok",
                "listing_type": "2BHK share",
                "occupation_requirement": "working professionals only",
                "calendar_slots": ["Saturday 4pm", "Sunday 5pm"],
                "commute_to_goregaon_mins": 16,
                "constraints": ["employed_only"],
                "negotiable": ["viewing_time"],
                "description": "2BHK share with one working professional, good commute to Goregaon East",
            },
        },
        initial_user_message="Hi, I’m looking for a flatmate-share in Andheri West or Jogeshwari. My budget is Rs. 20,000, I work in Goregaon East as a software engineer, and Saturday 4pm or Sunday 5pm are the only times I can visit.",
        seller_initial_message="Hi, I want help listing a new flatmate-share opening in Jogeshwari. The rent is around Rs. 19,500 for a 2BHK share, and visit slots are Saturday 4pm or Sunday 5pm.",
    ),
}
